### PR TITLE
Make thumbnail image smaller

### PR DESCRIPTION
**Pull request by mmarius**
The thumbnail was too large, this one is smaller.

### CODE REVIEW

**Comment by xhluca** [comment]
could you resolve the merge conflict?

**Comment by mmarius** [comment]
It tells me I can't. I replaced the file by a new file with the same name. Not sure why it shows that there is a conflict.

**Comment by xhluca** [comment]
in this case, perhaps undothe change and use a different file name?

**Comment by mmarius** [comment]
Is it not possible to force it to overwrite the existing file with the latest changes?

**Comment by xhluca** [comment]
i'm not sure... git diffs and binaries are over my head

**Comment by xhluca** [comment]
please recreate this pr

**Pull request closed without merging**
