### PR TITLE
Fix: `None` dates in `_posts/papers` leads to publication not being displayed

### PR DESCRIPTION
**Pull request by cesare-spinoso**
Fixes https://github.com/McGill-NLP/mcgill-nlp.github.io/issues/260

### CODE REVIEW

**Comment by cesare-spinoso** [comment]
@xhluca

**Comment by xhluca** [comment]
@cesare-spinoso can you run it locally?

**Comment by cesare-spinoso** [comment]
> @cesare-spinoso can you run it locally?

@xhluca  Good thinking since the fix actually broke the forms. GitHub issue template's default is index-based, not value-based. Works now:

image

image

(For manual updates)

image

**Comment by xhluca** [comment]
Thanks. You can try running the website on your local machine by following readme. If it's hard to understand let me know. You should be set up in 10-20min.

**Comment by cesare-spinoso** [comment]
> Thanks. You can try running the website on your local machine by following readme. If it's hard to understand let me know. You should be set up in 10-20min.

What am I running it locally for? To check that the 2 fixed posts are rendering correctly?

**Comment by xhluca** [comment]
@cesare-spinoso yes.

**Pull request merged**
