### PR TITLE
Create COMP 345 description.

### PR DESCRIPTION
**Pull request by kpraays**
Transferred the content from the course description doc to COMP 345 page.

### CODE REVIEW

**Comment by sivareddyg** [comment]
Thanks! Can you make this look as close as possible to https://github.com/McGill-NLP/mcgill-nlp.github.io/edit/main/_posts/teaching/2024-01-01-comp545-ling782-484-W24.md since some of the actions and template requires some metadata.

**Comment by kpraays** [comment]
Can you make this look as close as possible to https://github.com/McGill-NLP/mcgill-nlp.github.io/edit/main/_posts/teaching/2024-01-01-comp545-ling782-484-W24.md since some of the actions and template requires some metadata.? --> **done**

Have kept the same list for topics as in the doc.

**Comment by sivareddyg** [comment]
Table of contents look broken.
Screenshot 2024-01-03 at 5 17 38 PM

Live here https://mcgill-nlp.github.io/teaching/comp345-ling345-W24/

Please fix.

**Comment by sivareddyg** [comment]
Also, this stuff should appear

Screenshot 2024-01-03 at 5 19 58 PM

**Comment by kpraays** [comment]
Created a new pr with the changes requested. Added the remaining part and converted all heading to h1.

**Pull request merged**
