### PR TITLE
Add rg info [WIP]

### LINKED ISSUE #297: Update RG page
Add history of reading group to the reading group page. This is the rough history:
```
It was started by Jackie some time in 2015 (maybe summer of 2015 but you can double-check with him)
2016: Jad
2017: Ali
2018: Yue 
2019: Kushal (CompLing) & Arian Hosseini (LURG) [In Jan 2019 CompLing (McGill-specific) merged with LURG (Mila-wide)]
2020: Aishik & Arian
Jan 2021 - May 2022 : Ian & Arian
May 2022 - present: Vaibhav & Arian
```

### PR DESCRIPTION
**Pull request by cesare-spinoso**
Closes #297

### CODE REVIEW

**Comment by cesare-spinoso** [comment]
@xhluca is there a way to auto-scale the speadsheet iframe:
image
Also what do you think of the layout of the page?

**Comment by xhluca** [comment]
@cesare-spinoso we should use markdown tables automatically rendered by GH actions from some source (could be a JSON in the repo or hosted on Google drive). This should be very straightforward to add to the current workflow; and the frequency can be updated to once a day. 

Is the spreadsheet even required? It would be much better to put everything on the website IMO.

**Comment by xhluca** [comment]
Actually why don't we use the blog post format? Spreadsheets are hard to read and not mobile friendly. Markdown tables are slightly better if you want more conciseness, but the minimal mistakes blog format (which this template was built for) is perfect for this type of information.

**Comment by cesare-spinoso** [comment]
/home/c_spino/mcgill-nlp.github.io-fix/_includes/posts-publication-by-venue.html

Current semester list. List of different papers.

Then a list of previous semesters underneath.a

**Comment by cesare-spinoso** [comment]
@xhluca I have not exactly done what we have discussed. I am delaying the creation of the "Archive" portion at the bottom of the RG page. For now my priority is to get something working for the summer. Here is what it looks like:
image

As you can see, the current version uses a bit of a hack for the "More Information" link. I will fix this later. For now, this redirects to a page which looks like this (Notice the permalink) for the first speaker:
image

Do you have any input on how I can improve the layout. At the moment I am using `layout: single`. This is what happens when I remove that:
image

Thanks!

**Comment by xhluca** [comment]
Can you look at how this was done? https://github.com/McGill-NLP/mcgill-nlp.github.io/blob/main/_pages/teaching.md?plain=1

**Comment by cesare-spinoso** [comment]
Nice, that worked!

image

Lmk if you need me to do anything else.

**Comment by xhluca** [comment]
Can you make sure the tests pass? after that it should be ok

**Comment by cesare-spinoso** [comment]
Done, @xhluca

**Review by xhluca — APPROVED** [review]

**Pull request merged**
